spring:
  application:
    name: order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql
    url: jdbc:mysql://47.101.194.131:3306/springcloud?characterEncoding=utf-8&useSSL=false
    druid:
      max-active: 150
      initial-size: 10
      max-wait: 60000
      min-idle: 100
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
      #设置rabbitmq出错后重试的次数
        retry:
          max-attempts: 1
          #是否开启重试
          enabled: true
          #重试间隔
          initial-interval: 1000ms
          max-interval: 10000ms
        #重试后是否丢弃
        default-requeue-rejected: true
        max-concurrency: 50
        concurrency: 10
        prefetch: 1
        auto-startup: true
  redis:
    cluster:
      timeout: 1000
      nodes: 47.101.194.131:6379,47.101.194.131:6380,47.101.194.131:6381,47.101.194.131:6382,47.101.194.131:6383,47.101.194.131:6384
      max-redirects: 3
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 8
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0
#  redis:
#    host: localhost
#    port: 6379
#    jedis:
#      pool:
#        max-idle: 500
#        max-wait: 500ms
#        max-active: 1000
#    timeout: 5s
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic
