spring:
  application:
    name: order
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql
    url: jdbc:mysql://47.101.194.131:3306/springcloud?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 47.101.194.131
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
      #设置rabbitmq出错后重试的次数
        #retry:
          #max-attempts: 1
          #是否开启重试
          #enabled: false
          #重试间隔
          #initial-interval: 500ms
        #重试后是否丢弃
        default-requeue-rejected: true
  redis:
    host: 47.101.194.131
    port: 6379
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic  
