spring:
  application:
    name: order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql
    url: jdbc:mysql://47.101.194.131:3306/springcloud?characterEncoding=utf-8&useSSL=false
    druid:
      max-active: 200
      initial-size: 150
      max-wait: 60000
      min-idle: 100
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
  rabbitmq:
    host: 47.101.194.131
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
      #设置rabbitmq出错后重试的次数
        retry:
          max-attempts: 5
          #是否开启重试
          enabled: true
          #重试间隔
          initial-interval: 1000ms
          max-interval: 10000ms
        #重试后是否丢弃
        default-requeue-rejected: true
        max-concurrency: 10
        concurrency: 10
        prefetch: 1
        auto-startup: true
  redis:
    host: 47.101.194.131
    port: 6379
    jedis:
      pool:
        max-idle: 500
        max-wait: 500ms
        max-active: 500
    timeout: 5s
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic  
