spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql
    url: jdbc:mysql://47.101.194.131:3306/springcloud?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 47.101.194.131
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          max-attempts: 10
          enabled: true
          initial-interval: 500ms
        simple:
          default-requeue-rejected: true
  redis:
    host: 47.101.194.131
    port: 6379
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic  
