spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql
    url: jdbc:mysql://47.101.194.131:3306/springcloud?characterEncoding=utf-8&useSSL=false
  redis:
    host: 47.101.194.131
    port: 6379
