spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql
    url: jdbc:mysql://192.168.23.68:3306/springcloud?characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.23.68
    port: 6379
