spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=utf-8&useSSL=false
  redis:
    host: localhost
    port: 6379
